name: hostapd
version: 1.2
vendor: Kevin Lu <kevin.lu@canonical.com>
summary: hostapd for Snappy Ubuntu Core
description: re-package hostapd into snap for Snappy Ubuntu Core
icon: icon.png
binaries:
   hostapd: 
     exec: usr/sbin/hostapd
parts:
    hostapd:
        plugin: nil
        stage-packages:
          - hostapd
